#ifndef biases_tlscookie_h__
#define biases_tlscookie_h__

int generate_simultlscookie(PyArrayObject *pyarray, uint8_t key[16], unsigned int samples, PyObject *options);
int generate_simultlscookie_ref(PyArrayObject *pyarray, uint8_t key[16], unsigned int samples, PyObject *options);

/** Attempt to decrypt the cookie based on the stats generated by `simultlscookie1 */
PyObject * py_process_simultlscookie(PyObject *self, PyObject *args);

/** Quick attack simulation by simulating the multinomial distribution */
PyObject * py_simulate_cookie(PyObject *self, PyObject *args);

#endif // biases_tkiptsc_h__
